-- ====================================================================
-- SKEMA DATABASE UMATIS SERVERLESS (POSTGRESQL / SUPABASE)
-- ====================================================================
-- Jalankan script ini di SQL Editor Supabase Anda untuk membuat 
-- semua tabel, relasi, indeks, dan kebijakan keamanan (RLS).

-- 0. EXTENSIONS & ENUMS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enums
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
        CREATE TYPE user_role AS ENUM ('Admin / Owner', 'Staff');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'transaction_type') THEN
        CREATE TYPE transaction_type AS ENUM (
            'IN', 'OUT', 'TRANSFER',
            'POS_DEDUCTION', 'PURCHASE_IN', 'OPNAME_ADJ', 'POS_SALE',
            'WASTE', 'BREAKAGE', 'EXPIRED', 'COMP'
        );
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'stock_location') THEN
        CREATE TYPE stock_location AS ENUM ('RESTO', 'CENTRAL');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'invoice_status') THEN
        CREATE TYPE invoice_status AS ENUM ('DRAFT', 'SENT', 'RECEIVED', 'CANCELLED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'opname_status') THEN
        CREATE TYPE opname_status AS ENUM ('DRAFT', 'COUNTING', 'SUBMITTED', 'APPROVED');
    END IF;
END $$;

-- 0.5. POS TEMPLATES TABLE
CREATE TABLE IF NOT EXISTS public.pos_templates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) UNIQUE NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    column_mapping JSONB NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 1. TENANTS TABLE
CREATE TABLE IF NOT EXISTS public.tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) UNIQUE NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'active',
    pos_template_id UUID REFERENCES public.pos_templates(id) ON DELETE SET NULL,
    -- B-02: Lock Period — prevent retroactive edits after monthly close
    locked_until_month INT DEFAULT NULL,
    locked_until_year INT DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. USERS (PROFILE) TABLE
-- Terhubung dengan Supabase auth.users secara 1-ke-1
CREATE TABLE IF NOT EXISTS public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    role user_role DEFAULT 'Staff',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. MATERIALS TABLE
CREATE TABLE IF NOT EXISTS public.materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    supplier VARCHAR(255) NOT NULL,
    unit VARCHAR(100) NOT NULL,
    full_pack VARCHAR(255) NOT NULL,
    price DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    new_price DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    qty_resto DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    qty_central DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    min_stock DECIMAL(12, 2) NOT NULL DEFAULT 15.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, name)
);

-- 4. RECIPES TABLE
CREATE TABLE IF NOT EXISTS public.recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    menu_name VARCHAR(255) NOT NULL,
    pos_code VARCHAR(50) NULL,
    selling_price DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    subtotal DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    fix_cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    basic_cost DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    food_cost_pct DECIMAL(6, 4) NOT NULL DEFAULT 0.0000,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, menu_name)
);

-- 5. RECIPE INGREDIENTS TABLE
CREATE TABLE IF NOT EXISTS public.recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT REFERENCES public.recipes(id) ON DELETE CASCADE NOT NULL,
    material_id BIGINT REFERENCES public.materials(id) ON DELETE RESTRICT NOT NULL,
    qty_in_use DECIMAL(12, 4) NOT NULL,
    unit VARCHAR(100) NOT NULL,
    unit_price DECIMAL(12, 2) NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TRANSACTIONS (STOCK LEDGER) TABLE
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL,
    material_id BIGINT REFERENCES public.materials(id) ON DELETE SET NULL,
    type transaction_type NOT NULL,
    location stock_location NOT NULL,
    qty DECIMAL(12, 2) NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    notes TEXT,
    created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. INVOICES TABLE
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    invoice_no VARCHAR(255) NOT NULL,
    supplier VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    total DECIMAL(12, 2) NOT NULL,
    status invoice_status DEFAULT 'DRAFT',
    location stock_location DEFAULT 'CENTRAL',
    notes TEXT,
    received_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, invoice_no)
);

-- 8. INVOICE ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT REFERENCES public.invoices(id) ON DELETE CASCADE NOT NULL,
    material_id BIGINT REFERENCES public.materials(id) ON DELETE CASCADE NOT NULL,
    qty DECIMAL(12, 2) NOT NULL,
    unit_price DECIMAL(12, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
    action VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    ip_address VARCHAR(45),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. POS UPLOAD LOGS TABLE
CREATE TABLE IF NOT EXISTS public.pos_upload_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    filename VARCHAR(255) NOT NULL,
    file_hash VARCHAR(64) NOT NULL,
    period VARCHAR(100) NOT NULL,
    total_rows INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, file_hash)
);

-- 11. STOCK OPNAMES TABLE
CREATE TABLE IF NOT EXISTS public.stock_opnames (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    period_month INT NOT NULL,
    period_year INT NOT NULL,
    location stock_location NOT NULL,
    status opname_status DEFAULT 'DRAFT',
    signature_svg TEXT,
    created_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    approved_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
    submitted_at TIMESTAMPTZ,
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tenant_id, period_month, period_year, location)
);

-- 12. STOCK OPNAME ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.stock_opname_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opname_id BIGINT REFERENCES public.stock_opnames(id) ON DELETE CASCADE NOT NULL,
    material_id BIGINT REFERENCES public.materials(id) ON DELETE RESTRICT NOT NULL,
    book_qty DECIMAL(12, 4) NOT NULL,
    physical_qty DECIMAL(12, 4),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. BACKUPS TABLE
CREATE TABLE IF NOT EXISTS public.backups (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    filename VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    size_formatted VARCHAR(100) NOT NULL,
    data_json TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ====================================================================
-- PERFORMANCE INDEXES
-- ====================================================================
CREATE INDEX IF NOT EXISTS idx_materials_category ON public.materials(tenant_id, category);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON public.transactions(tenant_id, date);
CREATE INDEX IF NOT EXISTS idx_transactions_mat_date ON public.transactions(tenant_id, material_id, date);
CREATE INDEX IF NOT EXISTS idx_invoices_status ON public.invoices(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON public.audit_logs(tenant_id, action);
CREATE INDEX IF NOT EXISTS idx_stock_opnames_period ON public.stock_opnames(tenant_id, period_year, period_month);

-- ====================================================================
-- ROW LEVEL SECURITY (RLS) - ISOLASI TENANT
-- ====================================================================

-- Enable RLS
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recipe_ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_upload_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_opnames ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_opname_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.backups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pos_templates ENABLE ROW LEVEL SECURITY;

-- Helper Function to get tenant_id of authenticated user
CREATE OR REPLACE FUNCTION public.get_auth_tenant_id()
RETURNS UUID AS $$
    SELECT tenant_id FROM public.users WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER;

-- Policies for TENANTS (Users can read their own tenant)
CREATE POLICY tenant_read_policy ON public.tenants
    FOR SELECT USING (id = public.get_auth_tenant_id());

-- Policies for USERS (Users can read/write inside their own tenant)
CREATE POLICY users_policy ON public.users
    FOR ALL USING (tenant_id = public.get_auth_tenant_id() OR auth.uid() = id);

-- Policies for OTHER TABLES (Isolated by tenant_id)
CREATE POLICY materials_policy ON public.materials
    FOR ALL USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY recipes_policy ON public.recipes
    FOR ALL USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY recipe_ingredients_policy ON public.recipe_ingredients
    FOR ALL USING (
        recipe_id IN (SELECT id FROM public.recipes WHERE tenant_id = public.get_auth_tenant_id())
    );

CREATE POLICY transactions_policy ON public.transactions
    FOR ALL USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY invoices_policy ON public.invoices
    FOR ALL USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY invoice_items_policy ON public.invoice_items
    FOR ALL USING (
        invoice_id IN (SELECT id FROM public.invoices WHERE tenant_id = public.get_auth_tenant_id())
    );

CREATE POLICY audit_logs_policy ON public.audit_logs
    FOR ALL USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY pos_upload_logs_policy ON public.pos_upload_logs
    FOR ALL USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY stock_opnames_policy ON public.stock_opnames
    FOR ALL USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY stock_opname_items_policy ON public.stock_opname_items
    FOR ALL USING (
        opname_id IN (SELECT id FROM public.stock_opnames WHERE tenant_id = public.get_auth_tenant_id())
    );

CREATE POLICY backups_policy ON public.backups
    FOR ALL USING (tenant_id = public.get_auth_tenant_id());

CREATE POLICY pos_templates_policy ON public.pos_templates
    FOR SELECT USING (true);

-- ====================================================================
-- AUTHENTICATION TRIGGERS
-- ====================================================================
-- Otomatis sinkronisasi user profile ketika user baru mendaftar via Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
    v_tenant_id UUID;
    v_tenant_name VARCHAR;
    v_company_name VARCHAR;
    v_role user_role;
BEGIN
    -- Ambil metadata pendaftaran
    v_tenant_name  := COALESCE(new.raw_user_meta_data->>'tenant_name', new.raw_user_meta_data->>'company_name', 'default-resto');
    v_company_name := COALESCE(new.raw_user_meta_data->>'company_name', v_tenant_name);
    v_role         := COALESCE((new.raw_user_meta_data->>'role')::user_role, 'Admin / Owner'::user_role);

    -- Cari tenant berdasarkan nama atau buat baru jika registrasi pertama
    SELECT id INTO v_tenant_id FROM public.tenants WHERE name = LOWER(v_tenant_name);
    
    IF v_tenant_id IS NULL THEN
        -- Hubungkan ke template default saat registrasi pertama
        INSERT INTO public.tenants (name, company_name, status, pos_template_id)
        VALUES (
            LOWER(v_tenant_name), 
            v_company_name, 
            'active', 
            (SELECT id FROM public.pos_templates WHERE name = 'UMATIS_DEFAULT' LIMIT 1)
        )
        RETURNING id INTO v_tenant_id;
    END IF;

    -- Tambahkan user profile
    INSERT INTO public.users (id, tenant_id, name, email, role)
    VALUES (
        new.id,
        v_tenant_id,
        COALESCE(new.raw_user_meta_data->>'name', 'User Resto'),
        new.email,
        v_role
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger binding
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ====================================================================
-- SEED DATA - DEFAULT POS TEMPLATES
-- ====================================================================
INSERT INTO public.pos_templates (name, display_name, column_mapping) VALUES
('UMATIS_DEFAULT', 'UMATIS Standard POS (Row 12 Header)', '{
  "header_row_index": 12,
  "branch_col": "branch",
  "sales_date_col": "sales date",
  "menu_name_col": "menu name",
  "menu_code_col": "menu code",
  "qty_col": "qty",
  "total_col": "total"
}'),
('MOKA_POS', 'Moka POS (Row 0 Header)', '{
  "header_row_index": 0,
  "branch_col": "outlet",
  "sales_date_col": "date",
  "menu_name_col": "item",
  "menu_code_col": "sku",
  "qty_col": "quantity",
  "total_col": "gross sales"
}'),
('OLSERA_POS', 'Olsera POS (Row 0 Header)', '{
  "header_row_index": 0,
  "branch_col": "cabang",
  "sales_date_col": "tanggal",
  "menu_name_col": "nama produk",
  "menu_code_col": "sku",
  "qty_col": "jumlah",
  "total_col": "subtotal"
}'),
('PAWOON_POS', 'Pawoon POS (Row 0 Header)', '{
  "header_row_index": 0,
  "branch_col": "outlet",
  "sales_date_col": "tanggal transaksi",
  "menu_name_col": "nama menu",
  "menu_code_col": "sku",
  "qty_col": "jumlah terjual",
  "total_col": "total"
}')
ON CONFLICT (name) DO UPDATE 
SET display_name = EXCLUDED.display_name, column_mapping = EXCLUDED.column_mapping;

-- ====================================================================
-- UPGRADE SECTION (Run after initial schema if already deployed)
-- ====================================================================

-- Safely add new WASTE transaction types if enum already exists
DO $$ 
BEGIN
    -- Add new transaction types if they don't exist yet
    BEGIN ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'WASTE'; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'BREAKAGE'; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'EXPIRED'; EXCEPTION WHEN duplicate_object THEN NULL; END;
    BEGIN ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'COMP'; EXCEPTION WHEN duplicate_object THEN NULL; END;
END $$;

-- Add lock period columns to tenants if not exists
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS locked_until_month INT DEFAULT NULL;
ALTER TABLE public.tenants ADD COLUMN IF NOT EXISTS locked_until_year INT DEFAULT NULL;

-- ====================================================================
-- SUPER ADMIN: POS Template Management Policy
-- Allows super admin role to CREATE/UPDATE/DELETE pos_templates
-- ====================================================================

-- Policy: Super Admin (service_role) can manage all templates
DROP POLICY IF EXISTS "pos_templates_admin_policy" ON public.pos_templates;
CREATE POLICY "pos_templates_admin_policy"
    ON public.pos_templates
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- ====================================================================
-- ATOMIC RPC FUNCTIONS (T-02: Database Transactions for Data Integrity)
-- ====================================================================

-- Function 1: Atomic Invoice Receive
-- Ensures all stock updates + transaction inserts succeed or all roll back
CREATE OR REPLACE FUNCTION receive_invoice_atomic(
    p_invoice_id UUID,
    p_tenant_id UUID,
    p_user_id UUID
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_invoice RECORD;
    v_item RECORD;
    v_material RECORD;
    v_location TEXT;
    v_now TEXT;
    v_processed INT := 0;
BEGIN
    -- Lock invoice row
    SELECT * INTO v_invoice
    FROM public.invoices
    WHERE id = p_invoice_id AND tenant_id = p_tenant_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invoice tidak ditemukan: %', p_invoice_id;
    END IF;
    IF v_invoice.status = 'RECEIVED' THEN
        RAISE EXCEPTION 'Invoice sudah pernah diterima';
    END IF;
    IF v_invoice.status = 'CANCELLED' THEN
        RAISE EXCEPTION 'Tidak bisa memproses invoice yang dibatalkan';
    END IF;

    v_location := COALESCE(v_invoice.location, 'CENTRAL');
    v_now := CURRENT_DATE::TEXT;

    -- Process each invoice item atomically
    FOR v_item IN
        SELECT ii.*, m.qty_resto, m.qty_central, m.new_price, m.price, m.name
        FROM public.invoice_items ii
        JOIN public.materials m ON m.id = ii.material_id
        WHERE ii.invoice_id = p_invoice_id
    LOOP
        -- Update stock
        IF v_location = 'RESTO' THEN
            UPDATE public.materials
            SET qty_resto = qty_resto + v_item.qty,
                new_price = v_item.unit_price,
                updated_at = NOW()
            WHERE id = v_item.material_id;
        ELSE
            UPDATE public.materials
            SET qty_central = qty_central + v_item.qty,
                new_price = v_item.unit_price,
                updated_at = NOW()
            WHERE id = v_item.material_id;
        END IF;

        -- Insert transaction ledger entry
        INSERT INTO public.transactions (tenant_id, date, material_id, type, location, qty, amount, notes, created_by)
        VALUES (
            p_tenant_id, v_now, v_item.material_id, 'PURCHASE_IN', v_location::stock_location,
            v_item.qty,
            v_item.qty * v_item.unit_price,
            'Auto stock-in from invoice: ' || v_invoice.invoice_no,
            p_user_id
        );

        v_processed := v_processed + 1;
    END LOOP;

    -- Update invoice status
    UPDATE public.invoices
    SET status = 'RECEIVED', received_date = v_now, updated_at = NOW()
    WHERE id = p_invoice_id;

    RETURN json_build_object(
        'success', true,
        'invoice_no', v_invoice.invoice_no,
        'items_processed', v_processed,
        'location', v_location
    );
END;
$$;

-- Function 2: Atomic Stock Opname Completion
CREATE OR REPLACE FUNCTION complete_opname_atomic(
    p_opname_id UUID,
    p_tenant_id UUID,
    p_location TEXT,
    p_user_id UUID
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_item RECORD;
    v_variance NUMERIC;
    v_adjustments INT := 0;
    v_now TEXT;
BEGIN
    v_now := CURRENT_DATE::TEXT;

    -- Process each opname item
    FOR v_item IN
        SELECT soi.*, m.qty_resto, m.qty_central, m.new_price, m.price, m.name
        FROM public.stock_opname_items soi
        JOIN public.materials m ON m.id = soi.material_id
        WHERE soi.opname_id = p_opname_id
    LOOP
        IF p_location = 'RESTO' THEN
            v_variance := v_item.physical_qty - v_item.book_qty;
        ELSE
            v_variance := v_item.physical_qty - v_item.book_qty;
        END IF;

        IF ABS(v_variance) > 0.001 THEN
            -- Adjust material qty
            IF p_location = 'RESTO' THEN
                UPDATE public.materials
                SET qty_resto = v_item.physical_qty, updated_at = NOW()
                WHERE id = v_item.material_id;
            ELSE
                UPDATE public.materials
                SET qty_central = v_item.physical_qty, updated_at = NOW()
                WHERE id = v_item.material_id;
            END IF;

            -- Insert adjustment transaction
            INSERT INTO public.transactions (tenant_id, date, material_id, type, location, qty, amount, notes, created_by)
            VALUES (
                p_tenant_id, v_now, v_item.material_id, 'OPNAME_ADJ', p_location::stock_location,
                v_variance,
                v_variance * COALESCE(v_item.new_price, v_item.price, 0),
                'Stock Opname adjustment (Physical: ' || v_item.physical_qty || ', System: ' || v_item.book_qty || ')',
                p_user_id
            );

            v_adjustments := v_adjustments + 1;
        END IF;
    END LOOP;

    -- Mark opname as approved
    UPDATE public.stock_opnames
    SET status = 'APPROVED', approved_by = p_user_id, approved_at = NOW()
    WHERE id = p_opname_id;

    RETURN json_build_object(
        'success', true,
        'opname_id', p_opname_id,
        'adjustments_made', v_adjustments
    );
END;
$$;

-- Function 3: Check if a period is locked for a tenant
CREATE OR REPLACE FUNCTION is_period_locked(
    p_tenant_id UUID,
    p_year INT,
    p_month INT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE SECURITY DEFINER
AS $$
DECLARE
    v_locked_year INT;
    v_locked_month INT;
BEGIN
    SELECT locked_until_year, locked_until_month
    INTO v_locked_year, v_locked_month
    FROM public.tenants WHERE id = p_tenant_id;

    IF v_locked_year IS NULL THEN RETURN FALSE; END IF;

    -- Period is locked if it's before or equal to the lock boundary
    RETURN (p_year < v_locked_year)
        OR (p_year = v_locked_year AND p_month <= v_locked_month);
END;
$$;

-- Grant execute permissions to authenticated users
GRANT EXECUTE ON FUNCTION receive_invoice_atomic(UUID, UUID, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION complete_opname_atomic(UUID, UUID, TEXT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION is_period_locked(UUID, INT, INT) TO authenticated;

-- ====================================================================
-- END OF SCHEMA
-- ====================================================================
