-- Fase 4.3: Apply Backfill (JALANKAN HANYA SETELAH:
--   1. fase4_audit_recalc.json sudah direview manual.
--   2. Dijalankan di STAGING dulu, bukan production.
--   3. Mendapat approval dari penanggung jawab data keuangan.
-- 
-- Skrip ini mengembalikan amount yang salah akibat bug pack-size 2026-07 
-- dengan menyimpan nilai lama di kolom notes untuk audit trail.
-- 
-- Cara pakai:
--   1. Copy statement dari fase4_apply_backfill.sql yang di-generate skrip Node.js.
--   2. Jalankan di SQL Editor Supabase (staging dulu).
--   3. Verifikasi getCostControlReport() menghasilkan angka realistis.
--   4. Jika sudah valid, apply ke production.
--
-- CATATAN: Perubahan ini tidak dapat di-rollback otomatis setelah dieksekusi.
-- Pastikan backup database sudah dilakukan (Fase 0.1) sebelum menjalankan ini.

-- Contoh template (actual statements digenerate oleh fase4_backfill_dryrun.js):
-- UPDATE transactions
--   SET amount = <amount_baru>,
--       notes = COALESCE(notes, '') || ' [BACKFILL 2026-09: amount_lama=' || amount || ']'
--   WHERE id = <transaction_id>;

-- Setelah apply, catat di audit_logs (jika trigger immutability belum ada):
-- INSERT INTO audit_logs (tenant_id, user_id, action, description, created_at)
-- SELECT DISTINCT tenant_id, '<admin_user_id>', 'DATA_BACKFILL',
--   'Fase 4 backfill historis pack-size fix — diterapkan setelah review manual.',
--   now()
-- FROM transactions
-- WHERE id IN (<daftar id yang di-UPDATE>);

